<script type="text/javascript">
//Archivo: CambioIdioma.php
//Creado el : 19/11/2019
//Creado por: kn0l33
//Función: cambio de idioma en front
//-------------------------------------------------------


//por defecto el idioma es el español
var idioma = sessionStorage.getItem('idioma');
	if (idioma !== 'SPANISH' && idioma !== 'ENGLISH' && idioma !== 'GALLAECIAN') {
		sessionStorage.setItem('idioma', 'SPANISH');
}


//función para cambia al inglés
function cambioIngles() {
    var elemento;
    for (var id in english) {
        elemento = document.getElementById(id);
        if (elemento !== null) {
            elemento.innerHTML = english[id];
        }
    }

	sessionStorage.setItem('idioma', 'ENGLISH');

	var elem;
	for (var id in placeholders_en){
		elem = document.getElementById(id);
		if (elem !== null) {
			elem.placeholder = placeholders_en[id];
        }
	}
	
	
}

//función para cambiar al español
function cambioEspañol() {
    var elemento;
    for (var id in español) {
        elemento = document.getElementById(id);
        if (elemento !== null) {
            elemento.innerHTML = español[id];
        }
    }

	sessionStorage.setItem('idioma', 'SPANISH');

	var elem;
	for (var id in placeholders_es){
		elem = document.getElementById(id);
		if (elem !== null) {
			elem.placeholder = placeholders_es[id];
        }
	}
	
}

//función para cambiar al gallego
function cambioGalego() {
    var elemento;
    for (var id in galego) {
        elemento = document.getElementById(id);
        if (elemento !== null) {
            elemento.innerHTML = galego[id];
			
        }
    }

	sessionStorage.setItem('idioma', 'GALLAECIAN');

	var elem;
	for (var id in placeholders_gal){
		elem = document.getElementById(id);
		if (elem !== null) {
			elem.placeholder = placeholders_gal[id];
        }
	}
	
}


//funcion para mantener el idioma
function cargarIdioma() {
    var idioma_sesion = sessionStorage.getItem('idioma');
    if (idioma_sesion === 'SPANISH') { //si el idioma se sesion es el español
        cambioEspañol();
    } else if (idioma_sesion === 'ENGLISH') {//si el idioma se sesion es el ingles
        cambioIngles();
    } else if (idioma_sesion === 'GALLAECIAN') {//si el idioma se sesion es el gallego
        cambioGalego();
    }
}


var english ={
	'DNIl' : 'DNI',
	'CODESPACIOl' : 'Space code',
    'Portal de Gestion' : 'Management website',
	'Usuario no autenticado' : 'User not logged',
	'Ejemplo arquitectura IU' : 'IU architecture example',
	'Login' : 'Login',
	'Loginl' : 'Login',
	'login' : 'Login',
	'nombre' : 'Name',
	'apellidos' :'Surname',
	'email' : 'Email',
	'idioma' : 'Language',
	'Usuario' : 'User',
	'Ejemplo' : 'Example',
	'Otro' : 'Other',
	'INGLES' : 'ENGLISH',
	'ESPAÑOL' : 'SPANISH',
	'GALLEGO' : 'GALICIAN',
	'Volver' : 'Back',
	'Registro' : 'Register',
	'Gestion Asignatura IU' : 'User Interface Management',
	'Insertar usuario' : 'add user',
	'ADD' : 'ADD',
	'SHOWALL' : 'SHOLL ALL',
	'SHOWCURRENT' : 'VIEW DETAILS',
	'EDIT' : 'EDIT',
	'Gestion Usuarios' : 'User management',
	'Gestion Usuarios2' : 'User management',
	'SEARCH' : 'SEARCH',
	'DELETE' : 'DELETE',
	'Registrar': 'Sign up',
	'salir' : 'Log out',
	//-------------------- model messages
	'Error de gestor de base de datos' : 'Database Manager Error',
	'Inserción fallida: el elemento ya existe' : 'Insertion failed: item already exists',
	'Inserción realizada con éxito' : 'Success insert',
	'Borrado realizado con éxito' : 'Delete succesfully',
	'Actualización realizada con éxito' : 'update succesfully',
	'El login no existe' : 'The login dont exists',
	'La password para este usuario no es correcta' : 'Incorrect password for this login',
	'El usuario ya existe' : 'User exists',
	'DNI': 'DNI',
	'telefono':'telephone number',
	'FechaNacimiento':'Born date',
	'sexo':'sex',
	'Gestion Centros':'Center management',
	'Gestion Edificios':'Building Management',
	'Gestion Espacio':'Space Management',
	'Gestion Profesor':'Teacher Management',
	'Gestion  Espacio Profesor':'Teacher Space Management',
	'Estos atributos no pueden ser editados':'These attributes cannot be edited',
	'Gestion  Titulaciones Profesor':'Teacher Degrees Management ',
	'Gestion  Titulaciones':'Management Degrees',
	'Gestion Centros2':'Center management',
	'Gestion Edificios2':'Building Management',
	'Gestion Espacio2':'Space Management',
	'Gestion Profesor2':'Teacher Management',
	'Gestion  Espacio Profesor2':'Teacher Space Management',
	'Gestion  Titulaciones Profesor2':'Teacher Degrees Management ',
	'Gestion  Titulaciones2':'Management Degrees',
	'CODEDIFICIO':'Building Code',
	'CODCENTRO':'Center Code',
	'NOMBRECENTRO':'Center Name',
	'DIRECCIONCENTRO':'Center Address',
	'RESPONSABLECENTRO':'Responsible Center',
	'NOMBREEDIFICIO':'Building Name',
	'DIRECCIONEDIFICIO':'Building Address',
	'CAMPUSEDIFICIO':'Campus Building',
	'CODESPACIO':'Space Code',

	'CODEDIFICIOl':'Building Code',
	'CODCENTROl':'Center Code',
	'NOMBRECENTROl':'Center Name',
	'DIRECCIONCENTROl':'Center Address',
	'RESPONSABLECENTROl':'Responsible Center',
	'NOMBREEDIFICIOl':'Building Name',
	'DIRECCIONEDIFICIOl':'Building Address',
	'CAMPUSEDIFICIOl':'Campus Building',
	'CODESPACIOl':'Space Code',

	'TIPO':'Type',
	'Despacho':'Office',
	'Laboratorio':'Laboratory',
	'SUPERFICIEESPACIO':'Space Surface',
	'NUMINVENTARIOESPACIO':'Inventory Number Space',
	'SUPERFICIEESPACIOl':'Space Surface',
	'NUMINVENTARIOESPACIOl':'Inventory Number Space',
	'CODTITULACION':'Degrees Code',
	'ANHOACADEMICO':'Academic Year',
	'NOMBREPROFESOR':'Professor Name',
	'APELLIDOSPROFESOR':'Surname Professor',
	'AREAPROFESOR':'Professor Area',
	'DEPARTAMENTOPROFESOR':'Professor Department',

	'CODTITULACIONl':'Degrees Code',
	'ANHOACADEMICOl':'Academic Year',
	'NOMBREPROFESORl':'Professor Name',
	'APELLIDOSPROFESORl':'Surname Professor',
	'AREAPROFESORl':'Professor Area',
	'DEPARTAMENTOPROFESORl':'Professor Department',

	'PAS':'PAS',
	'NOMBRETITULACION':'Degree Name',
	'RESPONSABLETITULACION':'Head of Degree',

	'NOMBRETITULACIONl':'Degree Name',
	'RESPONSABLETITULACIONl':'Head of Degree',

	'Password':'Password',
	'Passwordl':'Password',
	'Nombre':'Name',
	'Nombrel':'Name',
	'Apellidos':'Surname',
	'Apellidosl':'Surname',
	'Telefono':'Phone',
	'Telefonol':'Phone',
	'Email':'Email',
	'Emaill':'Email',
	'Fecha nacimiento':'Birth date',
	'Fecha nacimientol':'Birth date',
	'Sexo':'Sex',
	'Hombre':'Man',
	'Mujer':'Woman',
	'Sexol':'Sex',
	'Hombrel':'Man',
	'Mujerl':'Woman',
	'No se puede eliminar: hay almenos una Titulacion asociada a este centro':'It cannot be eliminated: there is at least one Degree associated with this center',
	'No se puede eliminar: hay almenos un espacio asociado a este centro':'It cannot be deleted: there is at least one space associated with this center',
	'No se puede eliminar: hay un profesor asociado a este espacio':'It cannot be deleted: there is a teacher associated with this space',
	'No se puede eliminar: este profesor esta asociado a un espacio':'It cannot be deleted: this teacher is associated to a space or more',
	'No se puede eliminar: este profesor imparte un titulo':'Cannot be deleted: this teacher teaches a title or more',
	'No se puede eliminar: hay un profesor impartiendo este titulo':'It cannot be eliminated: there is a teacher teaching this title',
	'No se puede eliminar: hay al menos un espacio asociado a este edifico':'It cannot be deleted: there is at least one space associated with this building',
	'No se puede eliminar: hay al menos un centro asociado a este edifico':'It cannot be deleted: there is at least one center associated with this building',
	'BIENVENIDO A LA ARQUITECTURA BASE DE IU':'WELCOME TO THE BASE ARCHITECTURE OF IU',
	'Ejemplo arquitectura IU':'IU architecture example',
	'Hoy es':'Today is',
	'Edición fallida: el elemento ya existe':'Edition failed: the item already exists',
	'El DNI no cumple los requisitos' : 'The DNI does not meet the requirements',
	'Solo letras':'Only letters',
	'Solo numeros':'Only numbers',
	'Numeros y letras':'Numbers and letters',
	'Introduce tu DNI':'Enter your ID',
	'Introduce tu email':'Enter your email',
	'Introduce tu telefono':'Enter your phone',
	'fotopersonal' : 'Photo',
	'fotopersonall' : 'Photo',
	'El campo 1 no cumple con los requisitos':'Field 1 does not meet the requirements',
	'El campo 2 no cumple con los requisitos':'Field 2 does not meet the requirements',
	'El campo 3 no cumple con los requisitos':'Field 3 does not meet the requirements',
	'El campo 4 no cumple con los requisitos':'Field 4 does not meet the requirements',
	'El campo 5 no cumple con los requisitos':'Field 5 does not meet the requirements',
	'El campo 6 no cumple con los requisitos':'Field 6 does not meet the requirements',
	'El campo 7 no cumple con los requisitos':'Field 7 does not meet the requirements',
	'El campo 8 no cumple con los requisitos':'Field 8 does not meet the requirements',
	'El campo 9 no cumple con los requisitos':'Field 9 does not meet the requirements',
	'El login es vacio o tiene caracteres especiales':'The login is empty or has special characters',
	'La password es vacia o tiene caracteres especiales':'The password is empty or has special characters',
	'El DNI tiene que tener 8 numeros y 1 letra' : 'The ID must have 8 numbers and 1 letter',
	'El nombre solo puede tener letras':'The name can only have letters',
	'Los apellidos solo pueden tener letras':'Last names can only have letters',
	'El telefono debe de ser nacional':'The telephone must be national',
	'El emial tiene que tener @ y tener un dominio' :'The emial must have @ and have a domain',
	'Los codigos deben estar formados por letras y numeros': 'The codes must consist of letters and numbers',
	'Los codigos deben estar formados por letras y numeros2': 'The codes must consist of letters,numbers and "-"',
	'La direccion debe de ser solo letras':'The address must be only letters,numbers and  º ª - /',
	'El nombre del responsable solo puede ser letras':'The name of the person responsible can only be letters',
	'El campus solo puede ser letras':'The campus can only be letters',
	'La superficie tiene que ser un numero entre 1 y 100':'The surface has to be a number between 1 and 9999',
	'El inventario tiene que estar entre 1 y 100':'The inventory has to be between 1 and 99999999',
	'El area solo puede ser letras' : 'The area can only be letters',
	'El departamento solo puede ser letras' : 'The department can only be letters',
	'El año academico debe de ser letras y numeros' :'The academic year must be dddd-dddd',
	'Autor : z3oc9j' :'Author: kn0l33',
	'Página creada el 28/10/2019':'Page created on 10/28/2019',
	'Autor : z3oc9j  Página creada el 28/10/2019  Hoy es':'Author: kn0l33  Page created on 10/28/2019  Today is',
	'entidad fuerte' :'cannot be inserted because the code of the strong entity is missing',
	'ver centros' :'See centers',
	'ver espacios' :'See spaces',
	'ver espacios profesor':'See Teacher Space',
	'ver titulaciones': 'See Degrees',
	'ver profesor titulaciones':'See Teacher Degrees',
	'introduzca un sexo':'Enter a sex',
	'introduzca un tipo':'Enter a type',
	'fecha':'The format of the date is dd / mm / yyyy',
	'foto':'Enter a personal photo',
	'demasiado' : 'You have entered too many characters in the photo field',
	'actual' : 'Current photo',
	'nueva' : 'New photo'
};


var español={
	'DNIl' : 'DNI',
	'CODESPACIOl' : 'Codigo de espacio',
    'Portal de Gestion' : 'Portal de Gestion',
	'Usuario no autenticado' : 'Usuario no autenticado',
	'Ejemplo arquitectura IU' : 'Ejemplo arquitectura IU',
	'Login' : 'Login',
	'Loginl' : 'Login',
	'login' : 'Login',
	'nombre' : 'Nombre',
	'apellidos' :'Apellidos',
	'email' : 'Email',
	'idioma' : 'Idioma',
	'Usuario' : 'Usuario',
	'Ejemplo' : 'Ejemplo',
	'Otro' : 'Otro',
	'INGLES' : 'INGLES',
	'ESPAÑOL' : 'ESPAÑOL',
	'GALLEGO' : 'GALLEGO',
	'Volver' : 'Volver',
	'Registro' : 'Registro',
	'Gestion Asignatura IU' : 'Gestion Asignatura IU',
	'Insertar usuario' : 'Insertar usuario',
	'ADD' : 'Añadir',
	'SHOWALL' : 'Mostrar todos',
	'EDIT' : 'EDITAR',
	'Gestion Usuarios' : 'Gestion Usuarios',
	'Gestion Usuarios2' : 'Gestion Usuarios',
	'SEARCH' : 'BUSCAR',
	'DELETE' : 'BORRAR',
	'SHOWCURRENT' : 'DETALLE',
	'Registrar':'Registrar',
	'salir' : 'Salir',
	//------------------- mensajes modelo
	'Error de gestor de base de datos' : 'Error de gestor de base de datos',
	'Inserción fallida: el elemento ya existe' :'Inserción fallida: el elemento ya existe',
	'Inserción realizada con éxito' : 'Inserción realizada con éxito',
	'Borrado realizado con éxito' : 'Borrado realizado con éxito',
	'Actualización realizada con éxito' : 'Actualización realizada con éxito',
	'El login no existe' : 'El login no existe',
	'La password para este usuario no es correcta' : 'La password para este usuario no es correcta',
	'El usuario ya existe' : 'El usuario ya existe',
	'DNI': 'DNI',
	'telefono':'telefono',
	'FechaNacimiento':'FechaNacimiento',
	'sexo':'sexo',
	'Gestion Centros':'Gestión Centros',
	'Gestion Edificios':'Gestión Edificios',
	'Gestion Espacio':'Gestión Espacio',
	'Gestion Profesor':'Gestión Profesor',
	'Gestion  Espacio Profesor':'Gestión  Espacio Profesor',
	'Estos atributos no pueden ser editados':'Estos atributos no pueden ser editados',
	'Gestion  Titulaciones Profesor':'Gestión  Titulaciones Profesor',
	'Gestion  Titulaciones':'Gestión  Titulaciones',
	'Gestion Centros2':'Gestión Centros',
	'Gestion Edificios2':'Gestión Edificios',
	'Gestion Espacio2':'Gestión Espacio',
	'Gestion Profesor2':'Gestión Profesor',
	'Gestion  Espacio Profesor2':'Gestión  Espacio Profesor',
	'Gestion  Titulaciones Profesor2':'Gestión  Titulaciones Profesor',
	'Gestion  Titulaciones2':'Gestión  Titulaciones',
	'CODEDIFICIO':'Codigo Edificio',
	'CODCENTRO':'Codigo Centro',
	'NOMBRECENTRO':'Nombre Centro',
	'DIRECCIONCENTRO':'Direccion Centro',
	'RESPONSABLECENTRO':'Responsable Centro',
	'NOMBREEDIFICIO':'Nombre Edificio',
	'DIRECCIONEDIFICIO':'Direccion Edificio',
	'CAMPUSEDIFICIO':'Campus Edificio',
	'CODESPACIO':'Codigo Espacio',

	'CODEDIFICIOl':'Codigo Edificio',
	'CODCENTROl':'Codigo Centro',
	'NOMBRECENTROl':'Nombre Centro',
	'DIRECCIONCENTROl':'Direccion Centro',
	'RESPONSABLECENTROl':'Responsable Centro',
	'NOMBREEDIFICIOl':'Nombre Edificio',
	'DIRECCIONEDIFICIOl':'Direccion Edificio',
	'CAMPUSEDIFICIOl':'Campus Edificio',
	'CODESPACIOl':'Codigo Espacio',

	'TIPO':'Tipo',
	'Despacho':'Despacho',
	'Laboratorio':'Laboratorio',
	'SUPERFICIEESPACIO':'Superficie Espacio',
	'NUMINVENTARIOESPACIO':'Número Inventario Espacio',
	'SUPERFICIEESPACIOl':'Superficie Espacio',
	'NUMINVENTARIOESPACIOl':'Número Inventario Espacio',
	'CODTITULACION':'Codigo Titulacion',
	'ANHOACADEMICO':'Año Academico',
	'NOMBREPROFESOR':'Nombre Profesor',
	'APELLIDOSPROFESOR':'Apellidos Profesor',
	'AREAPROFESOR':'Area Profesor',
	'DEPARTAMENTOPROFESOR':'Departamento Profesor',

	'CODTITULACIONl':'Codigo Titulacion',
	'ANHOACADEMICOl':'Año Academico',
	'NOMBREPROFESORl':'Nombre Profesor',
	'APELLIDOSPROFESORl':'Apellidos Profesor',
	'AREAPROFESORl':'Area Profesor',
	'DEPARTAMENTOPROFESORl':'Departamento Profesor',

	'PAS':'PAS',
	'NOMBRETITULACION':'Nombre Titulacion',
	'RESPONSABLETITULACION':'Responsable Titulación',

	'NOMBRETITULACIONl':'Nombre Titulacion',
	'RESPONSABLETITULACIONl':'Responsable Titulación',

	'Password':'Contraseña',
	'Nombre':'Nombre',
	'Apellidos':'Apellidos',
	'Telefono':'Telefono',
	'Email':'Correo Electrónico',
	'Fecha nacimiento':'Fecha nacimiento',
	'Sexo':'Sexo',
	'Hombre':'Hombre',
	'Mujer':'Mujer',
	'Passwordl':'Contraseña',
	'Nombrel':'Nombre',
	'Apellidosl':'Apellidos',
	'Telefonol':'Telefono',
	'Emaill':'Correo Electrónico',
	'Fecha nacimientol':'Fecha nacimiento',
	'Sexol':'Sexo',
	'Hombrel':'Hombre',
	'Mujerl':'Mujer',
	'No se puede eliminar: hay almenos una Titulacion asociada a este centro':'No se puede eliminar: hay al menos una Titulacion asociada a este centro',
	'No se puede eliminar: hay almenos un espacio asociado a este centro':'No se puede eliminar: hay al menos un espacio asociado a este centro',
	'No se puede eliminar: hay un profesor asociado a este espacio':'No se puede eliminar: hay un profesor asociado a este espacio',
	'No se puede eliminar: este profesor esta asociado a un espacio':'No se puede eliminar: este profesor esta asociado a un espacio o mas',
	'No se puede eliminar: este profesor imparte un titulo':'No se puede eliminar: este profesor imparte un titulo o mas',
	'No se puede eliminar: hay un profesor impartiendo este titulo':'No se puede eliminar: hay un profesor impartiendo este titulo',
	'No se puede eliminar: hay al menos un espacio asociado a este edifico':'No se puede eliminar: hay al menos un espacio asociado a este edifico',
	'No se puede eliminar: hay al menos un centro asociado a este edifico':'No se puede eliminar: hay al menos un centro asociado a este edifico',
	'BIENVENIDO A LA ARQUITECTURA BASE DE IU':'BIENVENIDO A LA ARQUITECTURA BASE DE IU',
	'Ejemplo arquitectura IU':'Ejemplo arquitectura IU',
	'Hoy es':'Hoy es',
	'Edición fallida: el elemento ya existe':'Edición fallida: el elemento ya existe',
	'El DNI no cumple los requisitos' : 'El DNI no cumple los requisitos',
	'Solo letras':'Solo letras',
	'Solo numeros':'Solo números',
	'Numeros y letras':'Numeros y letras',
	'Introduce tu DNI':'Introduce tu DNI',
	'Introduce tu email':'Introduce tu email',
	'Introduce tu telefono':'Introduce tu telefono',
	'fotopersonal' : 'Foto',
	'fotopersonall' : 'Foto',
	'El campo 1 no cumple con los requisitos':'El campo 1 no cumple con los requisitos',
	'El campo 2 no cumple con los requisitos':'El campo 2 no cumple con los requisitos',
	'El campo 3 no cumple con los requisitos':'El campo 3 no cumple con los requisitos',
	'El campo 4 no cumple con los requisitos':'El campo 4 no cumple con los requisitos',
	'El campo 5 no cumple con los requisitos':'El campo 5 no cumple con los requisitos',
	'El campo 6 no cumple con los requisitos':'El campo 6 no cumple con los requisitos',
	'El campo 7 no cumple con los requisitos':'El campo 7 no cumple con los requisitos',
	'El campo 8 no cumple con los requisitos':'El campo 8 no cumple con los requisitos',
	'El campo 9 no cumple con los requisitos':'El campo 9 no cumple con los requisitos',
	'El login es vacio o tiene caracteres especiales':'El login es vacio o tiene caracteres especiales',
	'La password es vacia o tiene caracteres especiales':'La password es vacia o tiene caracteres especiales',
	'El DNI tiene que tener 8 numeros y 1 letra' : 'El DNI tiene que tener 8 numeros y 1 letra',
	'El nombre solo puede tener letras':'El nombre solo puede tener letras',
	'Los apellidos solo pueden tener letras':'Los apellidos solo pueden tener letras',
	'El telefono debe de ser nacional':'El telefono debe de ser nacional',
	'El emial tiene que tener @ y tener un dominio' :'El emial tiene que tener @ y tener un dominio',
	'Los codigos deben estar formados por letras y numeros': 'Los codigos deben estar formados por letras y numeros',
	'Los codigos deben estar formados por letras y numeros2': 'Los codigos deben estar formados por letras,numeros y "-"',
	'La direccion debe de ser solo letras':'La direccion debe de ser solo letras,numeros y  º ª - /',
	'El nombre del responsable solo puede ser letras':'El nombre del responsable solo puede ser letras',
	'El campus solo puede ser letras':'El campus solo puede ser letras',
	'La superficie tiene que ser un numero entre 1 y 100':'La superficie tiene que ser un numero entre 1 y 9999',
	'El inventario tiene que estar entre 1 y 100':'El inventario tiene que estar entre 1 y 99999999',
	'El area solo puede ser letras' : 'El area solo puede ser letras',
	'El departamento solo puede ser letras' : 'El departamento solo puede ser letras',
	'El año academico debe de ser letras y numeros' :'El año academico debe de ser dddd-dddd',
	'Autor : z3oc9j' : 'Autor : kn0l33',
	'Página creada el 28/10/2019':'Página creada el 28/10/2019',
	'Autor : z3oc9j  Página creada el 28/10/2019  Hoy es':'Autor : kn0l33  Página creada el 28/10/2019  Hoy es',
	'entidad fuerte':'no se puede insertar porque falta el código de la entidad fuerte',
	'ver centros' :'Ver centros',
	'ver espacios' :'Ver espacios',
	'ver espacios profesor':'Ver espacios profesor',
	'ver titulaciones': 'Ver titulaciones',
	'ver profesor titulaciones':'Ver profesor titulaciones',
	'introduzca un sexo':'Introduzca un sexo',
	'introduzca un tipo':'Introduzca un tipo',
	'fecha':'El formato de la fecha es dd/mm/aaaa',
	'foto':'Introduce una foto personal',
	'demasiado' : 'Has introducido demasiados caracteres en el campo foto',
	'actual' : 'Foto actual',
	'nueva' : 'Nueva foto'
};

var galego = {
	'DNIl' : 'DNI',
	'CODESPACIOl' : 'Codigo de espazo',
    'Portal de Gestion' : 'Portal de xestión',
	'Usuario no autenticado' : 'Usuario non autenticado',
	'Ejemplo arquitectura IU' : 'Exemplo de arquitectura IU',
	'Login' : 'Login',
	'Loginl' : 'Login',
	'login' : 'Login',
	'nombre' : 'Nome',
	'apellidos' :'Apelidos',
	'email' : 'Email',
	'idioma' : 'Lingua',
	'Usuario' : 'Usuario',
	'Ejemplo' : 'Exemplo',
	'Otro' : 'Outro',
	'INGLES' : 'INGLES',
	'ESPAÑOL' : 'ESPAÑOL',
	'GALLEGO' : 'GALEGO',
	'Volver' : 'Volver',
	'Registro' : 'Rexistro',
	'Gestion Asignatura IU' : 'Xestión Asignatura IU',
	'Insertar usuario' : 'Insertar usuario',
	'ADD' : 'Engadir',
	'SHOWALL' : 'Mostrar todos',
	'EDIT' : 'EDITAR',
	'Gestion Usuarios' : 'Xestión Usuarios',
	'Gestion Usuarios2' : 'Xestión Usuarios',
	'SEARCH' : 'BUSCAR',
	'DELETE' : 'BORRAR',
	'SHOWCURRENT' : 'DETALLE',
	'Registrar':'Rexistrar',
	'salir' : 'Saír',
	//------------------- mensajes modelo
	'Error de gestor de base de datos' : 'Erro do xestor de bases de datos',
	'Inserción fallida: el elemento ya existe' :'Fallou a inserción: o elemento xa existe',
	'Inserción realizada con éxito' : 'Inserción exitosa',
	'Borrado realizado con éxito' : 'Eliminación exitosa',
	'Actualización realizada con éxito' : 'Actualizouse correctamente',
	'El login no existe' : 'O login non existe',
	'La password para este usuario no es correcta' : 'O contrasinal para este usuario non é correcto',
	'El usuario ya existe' : 'O usuario xa existe',
	'DNI': 'DNI',
	'telefono':'telefono',
	'FechaNacimiento':'Data de nacemento',
	'sexo':'sexo',
	'Gestion Centros':'Xestión Centros',
	'Gestion Edificios':'Xestión Edificios',
	'Gestion Espacio':'Xestión Espacio',
	'Gestion Profesor':'Xestión Profesor',
	'Gestion  Espacio Profesor':'Xestión  Espazo Profesor',
	'Estos atributos no pueden ser editados':'Non se poden editar estes atributos.',
	'Gestion  Titulaciones Profesor':'Xestión  Titulacions Profesor',
	'Gestion  Titulaciones':'Xestión  Titulacions',
	'Gestion Centros2':'Xestión Centros',
	'Gestion Edificios2':'Xestión Edificios',
	'Gestion Espacio2':'Xestión Espacio',
	'Gestion Profesor2':'Xestión Profesor',
	'Gestion  Espacio Profesor2':'Xestión  Espazo Profesor',
	'Gestion  Titulaciones Profesor2':'Xestión  Titulacions Profesor',
	'Gestion  Titulaciones2':'Xestión  Titulacions',
	'CODEDIFICIO':'Codigo Edificio',
	'CODCENTRO':'Codigo Centro',
	'NOMBRECENTRO':'Nome Centro',
	'DIRECCIONCENTRO':'Direccion Centro',
	'RESPONSABLECENTRO':'Responsable Centro',
	'NOMBREEDIFICIO':'Nome Edificio',
	'DIRECCIONEDIFICIO':'Direccion Edificio',
	'CAMPUSEDIFICIO':'Campus Edificio',
	'CODESPACIO':'Codigo Espazo',

	'CODEDIFICIOl':'Codigo Edificio',
	'CODCENTROl':'Codigo Centro',
	'NOMBRECENTROl':'Nome Centro',
	'DIRECCIONCENTROl':'Direccion Centro',
	'RESPONSABLECENTROl':'Responsable Centro',
	'NOMBREEDIFICIOl':'Nome Edificio',
	'DIRECCIONEDIFICIOl':'Direccion Edificio',
	'CAMPUSEDIFICIOl':'Campus Edificio',
	'CODESPACIOl':'Codigo Espazo',

	'TIPO':'Tipo',
	'Despacho':'Despacho',
	'Laboratorio':'Laboratorio',
	'SUPERFICIEESPACIO':'Superficie Espazo',
	'NUMINVENTARIOESPACIO':'Número Inventario Espazo',
	'SUPERFICIEESPACIOl':'Superficie Espazo',
	'NUMINVENTARIOESPACIOl':'Número Inventario Espazo',
	'CODTITULACION':'Codigo Titulacion',
	'ANHOACADEMICO':'Ano Academico',
	'NOMBREPROFESOR':'Nome Profesor',
	'APELLIDOSPROFESOR':'Apelidos Profesor',
	'AREAPROFESOR':'Area Profesor',
	'DEPARTAMENTOPROFESOR':'Departamento Profesor',

	'CODTITULACIONl':'Codigo Titulacion',
	'ANHOACADEMICOl':'Ano Academico',
	'NOMBREPROFESORl':'Nome Profesor',
	'APELLIDOSPROFESORl':'Apelidos Profesor',
	'AREAPROFESORl':'Area Profesor',
	'DEPARTAMENTOPROFESORl':'Departamento Profesor',

	'PAS':'PAS',
	'NOMBRETITULACION':'Nome Titulacion',
	'RESPONSABLETITULACION':'Xefe de grao',

	'NOMBRETITULACIONl':'Nome Titulacion',
	'RESPONSABLETITULACIONl':'Xefe de grao',

	'Password':'Contrasinal',
	'Nombre':'Nome',
	'Apellidos':'Apelidos',
	'Telefono':'Telefono',
	'Email':'Correo Electrónico',
	'Fecha nacimiento':'Data de nacemento',
	'Sexo':'Sexo',
	'Hombre':'Home',
	'Mujer':'Muller',
	'Passwordl':'Contrasinal',
	'Nombrel':'Nome',
	'Apellidosl':'Apelidos',
	'Telefonol':'Telefono',
	'Emaill':'Correo Electrónico',
	'Fecha nacimientol':'Data de nacemento',
	'Sexol':'Sexo',
	'Hombrel':'Home',
	'Mujerl':'Muller',
	'No se puede eliminar: hay almenos una Titulacion asociada a este centro':'Non se pode eliminar: hai polo menos un grao asociado a este centro',
	'No se puede eliminar: hay almenos un espacio asociado a este centro':'Non se pode eliminar: hai polo menos un espazo asociado a este centro',
	'No se puede eliminar: hay un profesor asociado a este espacio':'Non se pode eliminar: hai un profesor asociado a este espazo',
	'No se puede eliminar: este profesor esta asociado a un espacio':'Non se pode eliminar: este profesor está asociado a un espazo ou mais',
	'No se puede eliminar: este profesor imparte un titulo':'Non se pode eliminar: este profesor ensina un título ou mais',
	'No se puede eliminar: hay un profesor impartiendo este titulo':'Non se pode eliminar: hai un profesor que ensina este título',
	'No se puede eliminar: hay al menos un espacio asociado a este edifico':'Non se pode eliminar: hai polo menos un espazo asociado a este edificio',
	'No se puede eliminar: hay al menos un centro asociado a este edifico':'Non se pode eliminar: hai polo menos un centro asociado a este edificio',
	'BIENVENIDO A LA ARQUITECTURA BASE DE IU':'BENVIDOS Á ARQUITECTURA DE BASE DE IU',
	'Ejemplo arquitectura IU' : 'Exemplo arquitectura IU',
	'Hoy es':'Hoxe é',
	'Edición fallida: el elemento ya existe':'Edición fallada: o elemento xa existe',
	'El DNI no cumple los requisitos' : 'O DNI non cumple os requisitos',
	'Solo letras':'Só letras',
	'Solo numeros':'Só números',
	'Numeros y letras':'Numeros e letras',
	'Introduce tu DNI':'Introduce o teu DNI',
	'Introduce tu email':'Introduce o teu email',
	'Introduce tu telefono':'Introduce o teu telefono',
	'fotopersonal' : 'Foto',
	'fotopersonall' : 'Foto',
	'El campo 1 no cumple con los requisitos':'O campo 1 non cumple cos requisitos',
	'El campo 2 no cumple con los requisitos':'O campo 2 non cumple cos requisitos',
	'El campo 3 no cumple con los requisitos':'O campo 3 non cumple cos requisitos',
	'El campo 4 no cumple con los requisitos':'O campo 4 non cumple cos requisitos',
	'El campo 5 no cumple con los requisitos':'O campo 5 non cumple cos requisitos',
	'El campo 6 no cumple con los requisitos':'O campo 6 non cumple cos requisitos',
	'El campo 7 no cumple con los requisitos':'O campo 7 non cumple cos requisitos',
	'El campo 8 no cumple con los requisitos':'O campo 8 non cumple cos requisitos',
	'El campo 9 no cumple con los requisitos':'O campo 9 non cumple cos requisitos',
	'El login es vacio o tiene caracteres especiales':'O inicio de sesión está baleiro ou ten caracteres especiais',
	'La password es vacia o tiene caracteres especiales':'O contrasinal está baleiro ou ten caracteres especiais',
	'El DNI tiene que tener 8 numeros y 1 letra' : 'O DNI debe ter 8 números e 1 letra',
	'El nombre solo puede tener letras':'O nome só pode ter letras',
	'Los apellidos solo pueden tener letras':'Os apelidos só poden ter letras',
	'El telefono debe de ser nacional':'O teléfono debe ser nacional',
	'El emial tiene que tener @ y tener un dominio' :'O emial debe ter @ e ter un dominio',
	'Los codigos deben estar formados por letras y numeros': 'Os codigos deben de ter letras e numeros',
	'Los codigos deben estar formados por letras y numeros2': 'Os codigos deben de ter letras,numeros e "-"',
	'La direccion debe de ser solo letras':'O enderezo debe ser só letras,números e º ª - /',
	'El nombre del responsable solo puede ser letras':'O nome do responsable só pode ser letras',
	'El campus solo puede ser letras':'O campus só pode ser de letras',
	'La superficie tiene que ser un numero entre 1 y 100':'A superficie ten que estar entre 1 e un 9999',
	'El inventario tiene que estar entre 1 y 100':'O inventario ten que estar entre 1 e 99999999',
	'El area solo puede ser letras' : 'A área só pode ser de letras',
	'El departamento solo puede ser letras' : 'O departamento solo pode ser letras',
	'El año academico debe de ser letras y numeros' :'O curso académico debe ser dddd-dddd',
	'Autor : z3oc9j' : 'Autor : kn0l33',
	'Página creada el 28/10/2019':'Páxina creada o 28/10/2019',
	'Autor : z3oc9j  Página creada el 28/10/2019  Hoy es':'Autor: kn0l33  Páxina creada o 28/10/2019  Hoxe é',
	'entidad fuerte':'Non se pode insertar porque falta o código da entidade forte',
	'ver centros' :'Ver centros',
	'ver espacios' :'Ver espazos',
	'ver espacios profesor':'Ver espazos profesor',
	'ver titulaciones': 'Ver titulacions',
	'ver profesor titulaciones':'Ver profesor titulacions',
	'introduzca un sexo':'Introduzca un sexo',
	'introduzca un tipo':'Introduzca un tipo',
	'fecha':'O formato de data é dd / mm / aaaa',
	'foto':'Introduce unha foto persoal',
	'demasiado' : 'Introduciu demasiados caracteres no campo da foto',
	'actual' : 'Foto actual',
	'nueva' : 'Nova foto'
};


var placeholders_es ={
	'login' : 'Solo letras',
	'password' : 'Solo letras',
	'DNI' : 'Introduce tu DNI',
	'nombre' : 'Solo letras',
	'apellidos' : 'Solo letras',
	'telefono' : 'Introduce tu telefono',
	'email' : 'Introduce tu email',
	'fotopersonal': 'Solo letras',
	'CODCENTRO': 'Numeros,letras y "-"',
	'CODEDIFICIO': 'Numeros,letras y "-"',
	'NOMBRECENTRO' : 'Solo letras',
	'DIRECCIONCENTRO' : 'Numeros,letras e º ª / -',
	'RESPONSABLECENTRO': 'Solo letras',
	'NOMBREEDIFICIO' : 'Solo letras',
	'DIRECCIONEDIFICIO' : 'Numeros,letras e º ª / -',
	'CAMPUSEDIFICIO' : 'Solo letras',
	'CODESPACIO' :'Numeros,letras y "-"',
	'SUPERFICIEESPACIO' :'Solo numeros',
	'NUMINVENTARIOESPACIO' : 'Solo numeros',
	'NOMBREPROFESOR' :'Solo letras',
	'APELLIDOSPROFESOR' :'Solo letras',
	'AREAPROFESOR' :'Solo letras',
	'DEPARTAMENTOPROFESOR':'Solo letras',
	'ANHOACADEMICO' : 'dddd-dddd',
	'CODTITULACION' : 'Numeros y letras',
	'NOMBRETITULACION' :'Solo letras', 
	'RESPONSABLETITULACION':'Solo letras',


};

var placeholders_gal ={
	'login' : 'Solo letras',
	'password' : 'Solo letras',
	'DNI' : 'Introduce o teu DNI',
	'nombre' : 'Solo letras',
	'apellidos' : 'Solo letras',
	'telefono' : 'Introduce e teu telefono',
	'email' : 'Introduce o teu email',
	'fotopersonal': 'Solo letras',
	'CODCENTRO': 'Numeros,letras e "-"',
	'CODEDIFICIO': 'Numeros,letras e "-"',
	'NOMBRECENTRO' : 'Solo letras',
	'DIRECCIONCENTRO' : 'Numeros,letras e º ª / -',
	'RESPONSABLECENTRO': 'Solo letras',
	'NOMBREEDIFICIO' : 'Solo letras',
	'DIRECCIONEDIFICIO' : 'Numeros,letras e º ª / -',
	'CAMPUSEDIFICIO' : 'Solo letras',
	'CODESPACIO' :'Numeros,letras e "-"',
	'SUPERFICIEESPACIO' :'Solo numeros',
	'NUMINVENTARIOESPACIO' : 'Solo numeros',
	'NOMBREPROFESOR' :'Solo letras',
	'APELLIDOSPROFESOR' :'Solo letras',
	'AREAPROFESOR' :'Solo letras',
	'DEPARTAMENTOPROFESOR':'Solo letras',
	'ANHOACADEMICO' : 'dddd-dddd',
	'CODTITULACION' : 'Numeros e letras',
	'NOMBRETITULACION' :'Solo letras', 
	'RESPONSABLETITULACION':'Solo letras',

};

var placeholders_en={
	'login' : 'Only letters',
	'password' : 'Only letters',
	'DNI' : 'Enter your ID',
	'nombre' : 'Only letters',
	'apellidos' : 'Only letters',
	'telefono' : 'Enter your phone',
	'email' : 'Enter your email',
	'fotopersonal': 'Only letters',
	'CODCENTRO': 'Numbers,letters and "-"',
	'CODEDIFICIO': 'Numbers,letters and "-"',
	'NOMBRECENTRO' : 'Only letters',
	'DIRECCIONCENTRO' : 'Numbers,letters and º ª / -',
	'RESPONSABLECENTRO': 'Only letters',
	'NOMBREEDIFICIO' : 'Only letters',
	'DIRECCIONEDIFICIO' : 'Numbers,letters and º ª / -',
	'CAMPUSEDIFICIO' : 'Only letters',
	'CODESPACIO' :'Numbers,letters and "-"',
	'SUPERFICIEESPACIO' :'Only numbers',
	'NUMINVENTARIOESPACIO' : 'Only numbers',
	'NOMBREPROFESOR' :'Only letters',
	'APELLIDOSPROFESOR' :'Only letters',
	'AREAPROFESOR' :'Only letters',
	'DEPARTAMENTOPROFESOR':'Only letters',
	'ANHOACADEMICO' : 'dddd-dddd',
	'CODTITULACION' : 'Numbers and letters',
	'NOMBRETITULACION' :'Only letters', 
	'RESPONSABLETITULACION':'Only letters',

};

</script>